Repository univCabi/FE, pull requests merged in 2024-11, with the labels that each got.

#18 Feat: svg/favicon 삽입, 검색 페이지 filter 구현#16
  index.html
  public/favicon.ico
  src/App.tsx
  src/components/Cabinet/SelectedCabinetInformation.tsx
  src/components/CabinetFooterMenuButton.tsx
  src/components/CabinetState/CabinetRental.tsx
  src/components/CabinetState/CabinetRentalComplete.tsx
  src/hooks/useCabinetRentalModal.tsx
  src/hooks/useCabinetReturnModal.tsx
  src/hooks/useCabinetStateManagement.tsx
  src/hooks/useSearchInput.tsx
  src/icons/angleDown.svg
  src/icons/cabiLogo.svg
  src/icons/cabinet.svg
  src/icons/log.svg
  src/icons/logout.svg
  src/icons/search.svg
  src/pages/MainPage.tsx
  src/pages/SearchPage.tsx
  src/pages/SideNavigationLayout.tsx
  svg.d.ts
  tsconfig.json
Labels: feat

#17 Feat: jwt login logout#12
  package-lock.json
  public/vite.svg
  src/api/loginApi.tsx
  src/components/LoginForm.tsx
  src/hooks/useLogin.tsx
  src/images/android-icon.png
  src/pages/Login/LoginPage.tsx
Labels: feat

#21 Feat: ProfilePage 구현#20
  src/App.tsx
  src/api/loginApi.tsx
  src/api/logoutApi.tsx
  src/api/userDataApi.tsx
  src/api/userDataSaveButtonApi.tsx
  src/components/CabinetFooterMenuButton.tsx
  src/components/LoginForm.tsx
  src/components/Profile/ProfileCard.tsx
  src/components/Profile/ProfileSaveButton.tsx
  src/components/Profile/RentalinfoCard.tsx
  src/components/ProfilePageButton.tsx
  src/hooks/useLogin.tsx
  src/hooks/useLoginState.tsx
  src/hooks/useLogout.tsx
  src/hooks/useProfileSave.tsx
  src/hooks/useUserData.tsx
  src/pages/Login/LoginPage.tsx
  src/pages/ProfilePage.tsx
  src/pages/SideNavigationLayout.tsx
Labels: feat

#22 Feat: ProfilePage 분기 기능과 토글 설명 추가#20
  src/api/userDataApi.tsx
  src/components/Profile/ProfileCard.tsx
  src/components/Profile/RentalinfoCard.tsx
  src/hooks/useUserData.tsx
Labels: feat

#25 Fix: Search Page 수정, 검색 API 구현#19
  package-lock.json
  package.json
  src/api/cabinetCallApi.tsx
  src/api/searchKeywordApi.tsx
  src/components/BuildingSelectButton.tsx
  src/components/Cabinet/CabinetButtonComponent.tsx
  src/components/Cabinet/SelectedCabinetInformation.tsx
  src/components/CabinetFooterMenuButton.tsx
  src/components/CabinetState/CabinetRental.tsx
  src/components/CabinetState/CabinetRentalComplete.tsx
  src/components/CabinetState/CabinetRentalConfirmModal.tsx
  src/components/Search/DefaultSearchComponent.tsx
  src/components/Search/SearchInput.tsx
  src/components/Search/SearchResultDropdownButton.tsx
  src/components/Search/SearchResultGridButton.tsx
  src/hooks/useBuildingList.tsx
  src/hooks/useBuildingState.tsx
  src/hooks/useCabinetRentalModal.tsx
  src/hooks/useCabinetState.tsx
  src/hooks/useSearch.tsx
  src/hooks/useSearchInput.tsx
  src/hooks/useSearchResultButton.tsx
  src/icons/angleDown.svg
  src/icons/search.svg
  src/mocks/buildingData.json
  src/pages/MainPage.tsx
  src/pages/SearchPage.tsx
  src/pages/SideNavigationLayout.tsx
Labels: feat, fix

#27 Fix: 병합 때 생긴 오류 수정
  src/pages/ProfilePage.tsx
  src/pages/SideNavigationLayout.tsx
Labels: fix

#30 Fix : 히스토리 페이지 css 수정 및 히스토리 페이지 프로필 페이지 api 요청 오류 해결
  package-lock.json
  package.json
  src/components/CabinetFooterMenuButton.tsx
  src/components/HistoryList.tsx
  src/components/Profile/RentalinfoCard.tsx
  src/hooks/useHistoryData.tsx
  src/hooks/useUserData.tsx
  src/index.css
  src/pages/HistoryPage.tsx
Labels: fix

#33 Feat: Search Page API 수정 및 무한스크롤 구현
  src/api/searchKeywordApi.tsx
  src/api/searchResultsApi.tsx
  src/components/BuildingSelectButton.tsx
  src/components/CabinetFooterMenuButton.tsx
  src/components/CabinetState/CabinetRental.tsx
  src/components/CabinetState/CabinetRentalComplete.tsx
  src/components/CabinetState/CabinetRentalConfirmModal.tsx
  src/components/Search/SearchResultGridButton.tsx
  src/hooks/useSearch.tsx
  src/hooks/useSearchInput.tsx
  src/hooks/useSearchResultButton.tsx
  src/hooks/useSearchToMain.tsx
  src/mocks/buildingData.json
  src/pages/SearchPage.tsx
  src/pages/SideNavigationLayout.tsx
Labels: feat

#36 Fix: 로그인 페이지 반응형 고도화
  src/components/LoginForm.tsx
Labels: fix

#34 Fix: 페이지 관련 layout 문제 해결
  src/api/userProfileInfoUpdateApi.tsx
  src/components/CabinetFooterMenuButton.tsx
  src/components/HistoryList.tsx
  src/components/Profile/ProfileSaveButton.tsx
  src/hooks/useProfileSave.tsx
  src/pages/HistoryPage.tsx
  src/pages/ProfilePage.tsx
Labels: fix

#41 Feat: 에러 페이지 ui 개선#40
  src/App.tsx
  src/components/Error/ErrorComponent.tsx
  src/components/Login/LoginForm.tsx
  src/components/Profile/ProfileCard.tsx
  src/components/Profile/RentalinfoCard.tsx
  src/pages/ErrorPage.tsx
  src/pages/Login/LoginPage.tsx
  tailwind.config.js
Labels: feat

#42 Fix: 프로필 글자 svg 변경 및 히스토리 페이지 date 변경
  package-lock.json
  package.json
  src/components/Error/ErrorComponent.tsx
  src/components/HistoryList.tsx
  src/components/Login/LoginForm.tsx
  src/components/Profile/RentalinfoCard.tsx
  src/components/ProfilePageButton.tsx
  src/hooks/useUserData.tsx
  src/icons/profile.svg
  src/images/android-icon.png
  src/pages/Login/LoginPage.tsx
Labels: fix

#45 Fix: date 관련 정보 수정
  src/components/HistoryList.tsx
  src/components/Profile/RentalinfoCard.tsx
  src/hooks/useUserData.tsx
Labels: fix

#43 Feat: 사물함 대여,반납 API#37
  src/api/cabinetCallApi.tsx
  src/api/cabinetDetailInfoApi.tsx
  src/api/rentApi.tsx
  src/api/returnApi.tsx
  src/api/searchKeywordApi.tsx
  src/components/BuildingSelectButton.tsx
  src/components/Cabinet/CabinetButtonComponent.tsx
  src/components/Cabinet/SelectedCabinetInformation.tsx
  src/components/CabinetFooterMenuButton.tsx
  src/components/CabinetState/CabinetRental.tsx
  src/components/CabinetState/CabinetRentalComplete.tsx
  src/components/CabinetState/CabinetRentalConfirmModal.tsx
  src/components/CabinetState/CabinetReturnConfirmModal.tsx
  src/components/Search/SearchInput.tsx
  src/components/Search/SearchResultDropdownButton.tsx
  src/components/Search/SearchResultGridButton.tsx
  src/hooks/useCabinetData.tsx
  src/hooks/useCabinetState.tsx
  src/hooks/useCabinetStateManagement.tsx
  src/hooks/useSearchResultButton.tsx
  src/mocks/buildingData.json
  src/pages/MainPage.tsx
  src/pages/SearchPage.tsx
  src/pages/SideNavigationLayout.tsx
Labels: feat, fix

#47 Feat: 프로필 저장 버튼 disabled 속성 추가
  src/components/Profile/ProfileSaveButton.tsx
Labels: feat

#49 Fix: cabinet button text-color 변경#48
  src/components/Cabinet/CabinetButtonComponent.tsx
  src/hooks/useCabinetData.tsx
  src/hooks/useCabinetState.tsx
Labels: fix
