Repository univCabi/FE, pull requests merged in 2025-01, with the labels that each got.

#52 Refactor: 로그인 로직 통합 및 SubmitAndNavigate 버튼 도입, Vite 재설정
  README.md
  eslint.config.js
  package-lock.json
  package.json
  src/App.tsx
  src/components/CabinetFooterMenuButton.tsx
  src/components/Login/LoginForm.tsx
  src/components/Profile/ProfileInfoCard.tsx
  src/components/Profile/ProfileSaveButton.tsx
  src/components/Profile/RentalinfoCard.tsx
  src/components/ProfilePageButton.tsx
  src/components/SubmitAndNavigateButton.tsx
  src/hooks/useHandleLogin.tsx
  src/hooks/useLoginState.tsx
  src/pages/Login/LoginPage.tsx
  src/pages/LoginPage.tsx
  src/pages/ProfilePage.tsx
  src/pages/SideNavigationLayout.tsx
  vite.config.ts
Labels: fix, refactor

#54 Refactor: 변수,함수명 리팩토링 + hook 분리
  src/api/rentApi.tsx
  src/api/returnApi.tsx
  src/api/searchKeywordApi.tsx
  src/components/BuildingSelectButton.tsx
  src/components/Cabinet/CabinetActionButtons.tsx
  src/components/Cabinet/CabinetButtonComponent.tsx
  src/components/Cabinet/CabinetButtonLayout.tsx
  src/components/Cabinet/CabinetInformationDisplay.tsx
  src/components/Cabinet/Modal/CabinetRentalConfirmModal.tsx
  src/components/Cabinet/Modal/CabinetReturnConfirmModal.tsx
  src/components/Cabinet/SelectedCabinetInformation.tsx
  src/components/CabinetFooterMenuButton.tsx
  src/components/Search/DefaultSearchLayout.tsx
  src/components/Search/SearchInputComponent.tsx
  src/components/Search/SearchResultDropdownButton.tsx
  src/components/Search/SearchResultGridButton.tsx
  src/hooks/useBuildingList.tsx
  src/hooks/useBuildingState.tsx
  src/hooks/useCabinetData.tsx
  src/hooks/useCabinetDetailData.tsx
  src/hooks/useCabinetRental.tsx
  src/hooks/useCabinetRentalModal.tsx
  src/hooks/useCabinetReturn.tsx
  src/hooks/useCabinetReturnModal.tsx
  src/hooks/useCabinetState.tsx
  src/hooks/useSearch.tsx
  src/hooks/useSearchInput.tsx
  src/hooks/useSearchResultButton.tsx
  src/pages/HistoryPage.tsx
  src/pages/MainPage.tsx
  src/pages/ProfilePage.tsx
  src/pages/SearchPage.tsx
  src/pages/SideNavigationLayout.tsx
Labels: fix, refactor

#53 Refactor: Confirm Modal 로직 병합 및 새로운 모달 생성
  src/components/Cabinet/Modal/CabinetRentalConfirmModal.tsx
  src/components/Cabinet/Modal/CabinetReturnConfirmModal.tsx
  src/components/Cabinet/SelectedCabinetInformation.tsx
  src/components/ConfirmModalView.tsx
  src/hooks/useCabinetRental.tsx
  src/hooks/useCabinetRentalModal.tsx
  src/hooks/useCabinetReturn.tsx
  src/hooks/useCabinetReturnModal.tsx
  src/hooks/useConfirmModalState.tsx
  src/pages/ProfilePage.tsx
  src/pages/SideNavigationLayout.tsx
Labels: feat, refactor

#56 Fix: Search 결과 버튼 클릭 -> 사물함 상세 정보 표시 에러 수정
  src/api/rentApi.tsx
  src/api/returnApi.tsx
  src/components/BuildingSelectButton.tsx
  src/components/Cabinet/CabinetButtonLayout.tsx
  src/components/CabinetFooterMenuButton.tsx
  src/hooks/useBuildingList.tsx
  src/hooks/useBuildingState.tsx
  src/hooks/useCabinet.tsx
  src/hooks/useCabinetActivation.tsx
  src/hooks/useCabinetDetailData.tsx
  src/hooks/useSearchResultButton.tsx
  src/mocks/buildingData.json
  src/pages/HistoryPage.tsx
  src/pages/MainPage.tsx
  src/pages/ProfilePage.tsx
  src/pages/SearchPage.tsx
  src/pages/SideNavigationLayout.tsx
Labels: fix

#57 타입 오류와 재사용성 개선, 레이아웃 통일성 개선
  src/components/BuildingSelectButton.tsx
  src/components/Cabinet/SelectedCabinetInformation.tsx
  src/components/HistoryList.tsx
  src/components/Login/LoginForm.tsx
  src/components/Profile/ProfileInfoCard.tsx
  src/components/Profile/RentalinfoCard.tsx
  src/components/Search/SearchResultDropdownButton.tsx
  src/hooks/useBuildingState.tsx
  src/hooks/useCabinet.tsx
  src/hooks/useSearchResultButton.tsx
  src/hooks/useSearchToMain.tsx
  src/hooks/useUserData.tsx
  src/mocks/buildingData.json
  src/pages/HistoryPage.tsx
  src/pages/MainPage.tsx
  src/pages/ProfilePage.tsx
  src/pages/SearchPage.tsx
  src/pages/SideNavigationLayout.tsx
  types/CabinetType.ts
  types/UserType.ts
Labels: fix, refactor

#59 Feat: HistoryList 무한 스크롤 구현#58
  src/api/userDataApi.tsx
  src/api/userHistoryDataApi.tsx
  src/components/HistoryList.tsx
  src/hooks/useHistoryData.tsx
  src/pages/HistoryPage.tsx
Labels: feat

#61 Feat: logger level에 따른 logger 도입#60
  src/api/cabinetCallApi.tsx
  src/api/cabinetDetailInfoApi.tsx
  src/api/loginApi.tsx
  src/api/rentApi.tsx
  src/api/returnApi.tsx
  src/api/searchKeywordApi.tsx
  src/api/searchResultsApi.tsx
  src/api/userDataApi.tsx
  src/api/userHistoryDataApi.tsx
  src/components/BuildingSelectButton.tsx
  src/hooks/useCabinet.tsx
  src/hooks/useCabinetActivation.tsx
  src/hooks/useCabinetRental.tsx
  src/hooks/useCabinetReturn.tsx
  src/hooks/useHandleLogin.tsx
  src/hooks/useHistoryData.tsx
  src/hooks/useLogout.tsx
  src/hooks/useProfileSave.tsx
  src/hooks/useSearch.tsx
  src/hooks/useSearchInput.tsx
  src/hooks/useSearchResultButton.tsx
  src/hooks/useUserData.tsx
  src/utils/logger.ts
Labels: feat

#63 Feat: CabinetButton, Profile 페이지 컴포넌트 스켈레톤 UI 구현
  src/components/Cabinet/CabinetButtonLayout.tsx
  src/components/Error/ErrorComponent.tsx
  src/components/Profile/ProfileInfoCard.tsx
  src/components/Profile/RentalinfoCard.tsx
  src/components/Skeleton/CabinetButtonSkeleton.tsx
  src/components/Skeleton/ProfileSkeleton.tsx
  src/hooks/useCabinetActivation.tsx
  src/hooks/useUserData.tsx
  src/pages/ProfilePage.tsx
  tailwind.config.js
Labels: feat

#65 로딩 스피너 구현
  src/components/HistoryList.tsx
  src/components/Login/LoginForm.tsx
  src/components/Search/SearchResultGridButton.tsx
  src/hooks/useHandleLogin.tsx
  src/hooks/useHistoryData.tsx
  src/hooks/useSearch.tsx
  src/pages/HistoryPage.tsx
Labels: feat
