Repository univCabi/FE, pull requests merged in 2025-04, with the labels that each got.

#94 Feat: Available Page 구현 #90
  src/App.tsx
  src/api/cabinetCallApi.tsx
  src/api/rentApi.tsx
  src/api/returnApi.tsx
  src/components/Admin/Cabinet/AdminCabinetInformationDisplay.tsx
  src/components/Admin/Cabinet/AdminCabinetLayout.tsx
  src/components/Admin/Cabinet/AdminSelectedCabinetInformation.tsx
  src/components/Admin/Cabinet/AdminStateManagementModal.tsx
  src/components/Available/AvailableCabinetLayout.tsx
  src/components/Available/AvailableCountdown.tsx
  src/components/BuildingSelectButton.tsx
  src/components/Cabinet/CabinetActionButtons.tsx
  src/components/Cabinet/CabinetButtonLayout.tsx
  src/components/Cabinet/SelectedCabinetInformation.tsx
  src/components/CabinetFooterMenuButton.tsx
  src/hooks/Admin/useAdminCabinet.tsx
  src/hooks/Admin/useAdminReturn.tsx
  src/hooks/Admin/useAdminStatus.tsx
  src/hooks/useAvailableCabinet.tsx
  src/hooks/useCabinet.tsx
  src/hooks/useCabinetActivation.tsx
  src/hooks/useCabinetRental.tsx
  src/hooks/useCabinetReturn.tsx
  src/hooks/useSearchResultButton.tsx
  src/hooks/useSearchToMain.tsx
  src/icons/available.svg
  src/icons/lock.svg
  src/icons/reload.svg
  src/index.css
  src/mocks/affiliatioinBuildingData.json
  src/pages/Admin/AdminMainPage.tsx
  src/pages/Admin/AdminSearchPage.tsx
  src/pages/AvailablePage.tsx
  src/pages/MainPage.tsx
  src/pages/SearchPage.tsx
  src/types/CabinetType.ts
  src/utils/formatDate.ts
Labels: feat

#95 Fix, Refactor : 토큰 인증 로직 개선 및 권한 없는 사용자 URL 리다이렉트 방지 구현
  package-lock.json
  package.json
  src/api/axiosInterceptApi.tsx
  src/hooks/useAuthRedirect.tsx
  src/layouts/MainLayout.tsx
  src/utils/cookies.ts
Labels: fix, refactor

#100 Fix: Netlify의 SPA 라우팅을 위한 _redirects 파일 추가
  public/_redirects
Labels: fix

#102 Fix, Feat: admin status api 조건 추가, 대여 error modal #92
  src/api/adminChangeStatusApi.tsx
  src/api/barChartDataApi.tsx
  src/components/Admin/Cabinet/AdminSelectedCabinetInformation.tsx
  src/components/Cabinet/CabinetButtonLayout.tsx
  src/components/Cabinet/SelectedCabinetInformation.tsx
  src/components/Modal/AlertModalView.tsx
  src/components/Modal/ConfirmModalView.tsx
  src/hooks/Admin/useAdminStatus.tsx
  src/hooks/useCabinetRental.tsx
  src/hooks/useSearchResultButton.tsx
  src/icons/error.svg
  src/pages/ProfilePage.tsx
  src/types/ModalType.ts
Labels: feat, fix

#104 ListTable 클릭시 해당 cabinet 요소 redirect 기능
  src/components/Admin/Cabinet/AdminCabinetLayout.tsx
  src/components/Cabinet/CabinetButtonLayout.tsx
  src/components/ListTableComponent.tsx
  src/pages/Admin/AdminMainPage.tsx
  src/pages/MainPage.tsx
Labels: feat
