Repository univCabi/FE, pull requests merged in 2025-03, with the labels that each got.

#77 Refactor: 재사용성을 위한 ListTable 추상화 작업#76
  src/components/Admin/AdminInfoChart.tsx
  src/components/HistoryList.tsx
  src/components/ListTableComponent.tsx
Labels: refactor

#79 Feat: 통계 막대 그래프 구현
  package-lock.json
  package.json
  src/components/Admin/AdminInfoChart.tsx
  src/components/Admin/CabinetBarChart.tsx
Labels: feat

#82 LoginForm 최적화
  src/components/Admin/AdminLoginForm.tsx
  src/components/Login/LoginForm.tsx
  src/pages/Admin/AdminLoginPage.tsx
  src/pages/LoginPage.tsx
Labels: refactor

#80 Feat: Admin Main Page 화면 구현#74
  src/components/Admin/AdminCabinetLayout.tsx
  src/components/Admin/Cabinet/AdminAllSelectButton.tsx
  src/components/Admin/Cabinet/AdminCabinetInformationDisplay.tsx
  src/components/Admin/Cabinet/AdminCabinetLayout.tsx
  src/components/Admin/Cabinet/AdminSelectedCabinetInformation.tsx
  src/components/Admin/Cabinet/AdminStateManagementModal.tsx
  src/components/BuildingSelectButton.tsx
  src/components/Cabinet/CabinetActionButtons.tsx
  src/components/Cabinet/CabinetButtonLayout.tsx
  src/components/Cabinet/CabinetInformationDisplay.tsx
  src/components/Cabinet/CabinetStatusInformation.tsx
  src/components/Cabinet/SelectedCabinetInformation.tsx
  src/components/CabinetFooterMenuButton.tsx
  src/components/ConfirmModalView.tsx
  src/components/Search/SearchResultDropdownButton.tsx
  src/components/Search/SearchResultGridButton.tsx
  src/components/SubmitAndNavigateButton.tsx
  src/contexts/SideNavigationLayoutContext.tsx
  src/hooks/useAdminCabinet.tsx
  src/hooks/useCabinet.tsx
  src/hooks/useCabinetActivation.tsx
  src/hooks/useCabinetRental.tsx
  src/hooks/useCabinetReturn.tsx
  src/hooks/useSearchResultButton.tsx
  src/icons/eachCheck.svg
  src/index.css
  src/pages/Admin/AdminMainPage.tsx
  src/pages/MainPage.tsx
  src/pages/SideNavigationLayout.tsx
  src/types/CabinetType.ts
  src/types/SearchType.ts
Labels: feat

#85 refactor: dashboard api 로부터 받은 값으로 barchart 랜더링#78
  src/api/barChartDataApi.tsx
  src/components/Admin/AdminInfoChart.tsx
  src/components/Admin/CabinetBarChart.tsx
  src/hooks/useBarChartData.tsx
  src/hooks/useCabinet.tsx
Labels: refactor

#86 Feat: 반납 API 연동 #83
  src/api/adminChangeStatusApi.tsx
  src/api/adminReturnApi.tsx
  src/components/Admin/Cabinet/AdminAllSelectButton.tsx
  src/components/Admin/Cabinet/AdminCabinetInformationDisplay.tsx
  src/components/Admin/Cabinet/AdminCabinetLayout.tsx
  src/components/Admin/Cabinet/AdminSelectedCabinetInformation.tsx
  src/components/Admin/Cabinet/AdminStateManagementModal.tsx
  src/components/Cabinet/SelectedCabinetInformation.tsx
  src/components/HistoryList.tsx
  src/components/Profile/RentalInfoCard.tsx
  src/hooks/useAdminCabinet.tsx
  src/hooks/useAdminReturn.tsx
  src/hooks/useAdminStatus.tsx
  src/hooks/useCabinet.tsx
  src/pages/Admin/AdminMainPage.tsx
  src/types/CabinetType.ts
  src/types/MultiCabinetType.ts
  src/types/StatusEnum.ts
  src/utils/formatDate.ts
Labels: feat

#88 Refactor: Admin/main 의 ListTable type, util 적용
  src/api/adminCabinetStatusListApi.tsx
  src/components/Admin/List/BrokenCabinetList.tsx
  src/components/HistoryList.tsx
  src/hooks/Admin/List/useBrokenCabinetListData.tsx
  src/hooks/Admin/List/useOverdueCabinetListData.tsx
  src/types/ListType.ts
Labels: refactor

#89 Feat: 상태관리 API 연동 #83
  src/api/adminChangeStatusApi.tsx
  src/components/Admin/Cabinet/AdminCabinetInformationDisplay.tsx
  src/components/Admin/Cabinet/AdminCabinetLayout.tsx
  src/components/Admin/Cabinet/AdminSelectedCabinetInformation.tsx
  src/components/Admin/Cabinet/AdminStateManagementModal.tsx
  src/components/Cabinet/CabinetButtonLayout.tsx
  src/components/Cabinet/SelectedCabinetInformation.tsx
  src/hooks/useAdminStatus.tsx
  src/hooks/useCabinet.tsx
  src/hooks/useCabinetActivation.tsx
  src/pages/Admin/AdminMainPage.tsx
  src/types/StatusEnum.ts
Labels: feat

#91 Fix: Admin 전체 선택시 사물함 정보가 바로 보이도록 수정
  src/components/Admin/Cabinet/AdminAllSelectButton.tsx
  src/components/Admin/Cabinet/AdminCabinetLayout.tsx
  src/components/Admin/Cabinet/AdminSelectedCabinetInformation.tsx
  src/components/Admin/Cabinet/AdminStateManagementModal.tsx
  src/hooks/useAdminCabinet.tsx
  src/hooks/useAdminStatus.tsx
  src/pages/Admin/AdminMainPage.tsx
Labels: fix
